# Generated by Django 5.0.7 on 2024-07-10 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(auto_now_add=True, default=-2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
