# Generated by Django 5.0.3 on 2024-05-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_identifier',
            new_name='student_id',
        ),
    ]
