# Generated by Django 5.0.3 on 2024-07-08 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_test_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
