# Generated by Django 5.0.3 on 2024-06-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_test_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='grade',
            field=models.CharField(default="ז'", max_length=100),
            preserve_default=False,
        ),
    ]
