# Generated by Django 5.0.3 on 2024-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_answer_approved_eval_answer_origin_eval'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
