# Generated by Django 5.0.6 on 2024-06-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_test_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="date",
            field=models.DateField(default=-2000),
            preserve_default=False,
        ),
    ]
