# Generated by Django 5.0.3 on 2024-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_answer_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
