# Generated by Django 5.0.6 on 2024-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_test_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
