# Generated by Django 5.0.6 on 2024-06-12 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_test_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="date",
        ),
    ]
