# Generated by Django 5.0.3 on 2024-05-15 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_student_email_student_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='creation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='test',
            unique_together={('title', 'teacher')},
        ),
    ]
