# Generated by Django 5.0.3 on 2024-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_test_creation_date_alter_test_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
