# Generated by Django 5.0.3 on 2024-05-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_test_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
