# Generated by Django 5.0.6 on 2024-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0009_test_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="date",
            field=models.CharField(default=-2000, max_length=100),
            preserve_default=False,
        ),
    ]
