# Generated by Django 5.0.6 on 2024-06-29 01:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0010_test_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="test",
            name="date",
        ),
        migrations.RemoveField(
            model_name="test",
            name="link",
        ),
    ]
