# Generated by Django 5.0.3 on 2024-05-15 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_student_id_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='link',
        ),
    ]
