# Generated by Django 5.0.3 on 2024-05-15 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_remove_test_creation_date_remove_test_link'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='test',
            unique_together=set(),
        ),
    ]
