# Generated by Django 5.0.3 on 2024-05-17 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_student_id_alter_student_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='test',
            new_name='testbox',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='email',
            new_name='student_identifier',
        ),
    ]
